<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Controller\PostController'     => __DIR__ . '/Market/src/Market/Controller/PostController.php',
    'Market\Controller\ViewController'     => __DIR__ . '/Market/src/Market/Controller/ViewController.php',
    'Market\Factory\PostControllerFactory' => __DIR__ . '/Market/src/Market/Factory/PostControllerFactory.php',
);
